
compiler c   wcc386 "-fo=%s -zp1 -d1 -w3 -s -oilrte -5s -j -zq -d__B_AVLIB"
compiler cpp wpp386 "-fo=%s -zp1 -d1 -w2 -s -oilrte -5s -j -zq -d__B_AVLIB -i=c:\\dxsdk\\inc"
compiler asm tasm ",%s /ml/q/z/zi/t/m5"
linker opt "op q"

list common{
  cpuid averrmsg readstrz config
}

list win{
  keybwin
}

list dos{
  keyb harderr mouse
}

library av dos common
  obj dir "tmpdos\\"
  exe "..\\dos\\av.lib"

library avwin win common
  obj dir "tmpwin\\"
  exe "..\\win\\av.lib"
  opt cpp def "-bt=nt"
  opt c   def "-bt=nt"

link avdll win common
  "d a system nt_dll_avl library dinput,dxguid"
  obj dir "tmpdll\\"
  exe "..\\win\\av.dll"
  make library "..\\win\\avdll"
  opt cpp def "-bt=nt -br -bd"
  opt c   def "-bt=nt -br -bd"
  opt asm def "/d__DLL__"

project all avdll avwin av
